version:             0.1.0.0
author:              "0xmycf"
name:                "aoc22"
github:              "0xmycf/aoc22"
license:             "CC-BY-NC-SA-4.0"
synopsis:            "Just a simple project"
copyright:           "2022 0xmycf"
homepage:            https://github.com/0xmycf/advent-of-code#readme

extra-source-files:
- README.md          

language: GHC2021
default-extensions:
  - MultiWayIf
  - BlockArguments
  - DerivingStrategies
  - LambdaCase
  - OverloadedStrings
  - OverloadedLabels
  - RecordWildCards
  - ExplicitNamespaces
  - GADTs
  - DataKinds
  - TypeFamilies
  - DeriveAnyClass
  - TemplateHaskell

description:         Please see the README on GitHub at <https://github.com/0xmycf/aoc22#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- transformers
- matrix
- containers
- unordered-containers
- hashable
- directory
- parsec
- linear
- vector
- text
- split
- lens
- generic-lens
- neat-interpolation
- say
- async
- parallel
- deepseq
- psqueues
- range
- data-interval
- data-default
- extended-reals

ghc-options:
- -Wall

library:
  source-dirs: src
  dependencies:
  - directory

executables:
  aoc22-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

    dependencies:
    - aoc22

tests:
  aoc22-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc22
    - QuickCheck
    - hspec

benchmarks:
  aoc22-bench:
    main:                Bench.hs
    source-dirs:         bench
    ghc-options:
    - -O2
    dependencies:
    - aoc22
    - criterion
