name = "day08"
version = "1.0.0"
gleam = ">= 1.1.0"

[dependencies]
gleam_stdlib = ">= 0.46.0 and < 1.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
shellout = ">= 1.6.0 and < 2.0.0"
gleam_erlang = ">= 0.33.0 and < 1.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
